sonar.projectKey=chanchal-2512_finance-tracker
sonar.organization=chanchal-2512
sonar.projectName=Finance Tracker
sonar.projectVersion=1.0

sonar.sources=backend,frontend/src
sonar.exclusions=**/node_modules/**,**/build/**,**/.git/**,**/data/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
